module.exports.config = {
  name: "ARIF-BOT-2",
  version: "5.0.0",
  hasPermssion: 0,
  credits: "ARIF BABU",
  description: "MADE BY ARIF BABU",
  commandCategory: "No command marks needed",
  cooldowns: 0
};

const responses = [
  "TUM MERE BOSS ZAKHMI SAYAR KI GF BAN JAO LDKI🙈",
  "Bot nah bol oye, Janu bol mujhy 🥺",
  "Haweli pe mil zara bataunga 😂",
  "Shakal se masoom lagte ho 😂",
  "Kash tum single hote to maza hi kuch aur tha 😂",
  "Ab yaad ayi meri? Pehle to babu shona me busy the 😾",
  "Roti banana ke liye aate me paani daalte hain 😂",
  "Aise na dekho pyaar ho jayega 😂",
  "Teri pic dekhne se pehle shukar hai mai andha hu 😂",
  "Haste raho, hasne se bill nahi aata 😂",
  "Mujhse shadi karlo, daily chocolate dunga 🍫",
  "Ajao pizza khilau apko 🍕",
  "Duniya me sab khatam ho sakta, logo ki bakwas nahi 😂",
  "Everything is temporary, but katna is permanent 😂",
  "Ameer larki set karke sab ka udhar wapis karunga 😔",
  "Lagta hai career bhi Titanic ki tarah doob gaya 💔",
  "Itna single hu khwab me bhi ladki han kare to ankh khul jati 🙂",
  "Move on karle bhai kab tak uski profile dekhega",
  "Bot jaan hai sabki 🌸",
  "Ib ajao chup chup ke baatein karte hain 🙈",
  "Ji ji hukam karo 😂",
  "Fikr na karo kuch theek nahi hoga 😂😂",
  "Tum na single hi maroge 😂",
  "Tujhe aur koi kaam nahi hai? Har waqt bot bot 😒",
  "Tumhare bina group suna suna lagta hai janu 😜",
  "Mehfil me chaar chaand laga diye tumne aake 🌙",
  "Dil garden garden ho gaya tumhe dekh ke 🌸",
  "Aaj toh bada handsome lag raha hai tu 😎",
  "Single hai ya mingle? Jhoot mat bolna 😏",
  "Chai pani puch lo, itna kanjoos mat bano ☕",
  "Tumhari yaad me raat bhar so nahi paya 😴",
  "Haye tumhari ye ada, maar hi dalegi ek din 😍",
  "Meri battery low hai, tumhara dil charger hai kya? 🔋",
  "Group ka star hai tu 🌟",
  "Itna cute DP kisne lagane bola tha 😍",
  "Tumhari smile pe duniya qurban 🥰",
  "Dekh ke dil khush ho gaya ❤️",
  "Aaj toh party banti hai 🎉",
  "Tumhara naam dil pe likh diya hai maine 💖",
  "Haye garmi, tum itne hot kyun ho 🔥",
  "Bas karo, itna mat hasao pet dukh raha hai 🤣",
  "Tumhari baaton me jadoo hai ✨",
  "Tum toh meri jaan ho yaar 😘",
  "Aaj toh tum full form me ho 😎",
  "Tum toh mera din bana dete ho",
  "Yaar tum kitne cute ho 🥺",
  "Tum toh dil jeet lete ho har baar ❤️",
  "Tum toh chand ka tukda ho 🌙",
  "Oye janeman, kya haal hai? 😜",
  "Aaj toh tum aag laga rahe ho 🔥",
  "Tumhari smile killer hai 😍",
  "Tum toh hero ho is group ke 😎",
  "Dil me bas tum hi tum ho 💚",
  "Tum toh dil ka sukoon ho 🥰",
  "Oye paglu, kya kar raha hai? 😂",
  "Tum toh jaan ho meri 😘",
  "Tum toh meri duniya ho 🌍",
  "Tum toh meri khushi ho 😁",
  "Oye shona, kahan gayab ho? 🥺",
  "Tum toh pyaar ke layak ho ❤️",
  "Tum toh meri dua ho 🤲",
  "Tum toh meri muskurahat ho 😊",
  "Oye heroine, kya haal hai? 😍",
  "Aaj toh tumne aag laga di 🔥",
  "Tum toh dil ki raani ho 👑",
  "Tum toh meri zindagi ka pyaar ho",
  "Tumhari baatein dil ko chhoo jati hain",
  "Oye cute, suno na 🥰",
  "Tum toh meri raat ka chand ho 🌙",
  "Tum toh dil ki dhadkan ho 💓",
  "Tum toh meri subah ho ☀️",
  "Oye jaanu, miss you 🥺",
  "Tum toh dil ke kareeb ho",
  "Zakhmi Sayar ka bot tumhe yaad kar raha tha 🥰",
  "Zakhmi ki shayari sunoge? Dil khush ho jayega 📝",
  "Zakhmi Sayar ki mehfil me swagat hai 🌟",
  "Zakhmi ka naam sunte hi dil garden ho jata hai ❤️",
  "Zakhmi Sayar ke liye ek like banta hai 👍",
  "Dil toota hai Zakhmi ka, tum mat todna 💔",
  "Tum Zakhmi ke dost ho isliye mere bhi dost ho 🤗",
  "Zakhmi Sayar ka dil bahut bada hai 💖",
  "Zakhmi Sayar ki taraf se salaam 🙏",
  "Zakhmi ka bot best hai 😎",
  "Zakhmi Sayar ki jaan ho tum 😘",
  "Zakhmi ki shayari, tumhari hansi 😂",
  "Tum Zakhmi ke bina adhoore ho 😜",
  "Zakhmi Sayar ka fan hu mai bhi 😍",
  "Zakhmi Sayar ki duniya me swagat hai 🌍",
  "Tum toh Zakhmi se bhi zyada cute ho 🙈",
  "Zakhmi Sayar - Shayari ka Badshah 📝",
  "Zakhmi ka status dekha kya? 🔥",
  "Zakhmi Sayar ko follow karo, maza ayega 😎",
  "Aaj kal dil zakhmi hai, dawai tum ho 🥺",
  "Tum toh dil ki marham ho 🤗",
  "Tumse milke sukoon mila 😌",
  "Tum toh meri favourite ho 🌸",
  "Bas tumhari kami thi mehfil me 🎉",
  "Tum toh full mood me ho 😎",
  "Oye hoye kya baat hai 😜",
  "Tum toh dil me bas gaye ho ❤️",
  "Aaj toh kamaal kar diya 👌",
  "Tumse zyada cute koi nahi 🙈",
  "Tum toh star ho group ke 🌟",
  "Tum toh jaan ho meri jaan 😘",
  "Tumse baat karke din ban gaya ☀️",
  "Tum toh meri shaam ho 🌆",
  "Tum toh meri jannat ho 😍",
  "Tum toh meri kahani ho 📖",
  "Tum toh meri khwahish ho 💫",
  "Tum toh pyaar ho mera ❤️",
  "Tum toh meri har dua ho 🤲",
  "Tum toh meri muskan ho 😊"
];

const emojiReplies = {
  "😂": "kyu haas rahe ho pagal ho gaye kya 😂",
  "🤣": "has has ke pet phat jayega tera 🤣",
  "😍": "IS NAZAR SE MERE BOSS ZAKHMI KO DEKHO 😍",
  "🥰": "oooh aaj toh bada pyaar aa rha hai 🥰",
  "😘": "Pehle brush karke aa 😘😂",
  "❤️": "MEKO KALA DIL CHAHIYE 🙂 LAL TOOT JATA HAI ❤️",
  "dua": "Dua mere owner imran boss ki gf hai unse izzat se bat krna 🙄wrna boss id uda denge🤞😒",
  "@Sitara Noor": "Sitara noor mere boss ki ekloti sali hai🙈or sitara bhot cute hai 💞🫶",
  "@Dua Khan": "Dua khan bhot cute ladki hai mere owner imran se bhot pyar karti hai dua mere boss bhi dua se bhot pyar krte hai🥵🙈",
  "🖤": "kala dil wale sach wala pyaar karte hain 🖤",
  "💔": "dil toot gaya to fevicol se jod do 💔",
  "😏": "Sda hua muh kyu bana rhe ho 😏",
  "🙄": "Zakhmi Boss busy hai mujhse baat karo 🙄",
  "😒": "samne hu to samne dekh na 😒",
  "🤔": "Sochiye mat, Zakhmi se pucho 🤔",
  "😎": "Chasma hatao na sahab 😎",
  "🥺": "itne bhi masoom nahi ho jitna muh bana rahe ho 🥺",
  "😭": "kya hua ro kyu rahe ho, me hu na 😭",
  "😢": "meri jaan sad mat ho 🤗",
  "😡": "me toh mazak kar rahi thi 😡",
  "🤬": "gali na de, Zakhmi ko bata dungi 🤬",
  "😴": "nind aa rahi hai to so jawo na 😴",
  "🤤": "Muh se supari nikal re baba 🤤",
  "😋": "ghar walo ne khana nahi diya kya 😋",
  "🤗": "yahan nahi ib chalo hug karne 🙈🤗",
  "😮": "muh me makkhi ghus jayegi band karo 😮",
  "😱": "kya hua bhoot dekh liya kya 👻",
  "👍": "tusi awesome ho g 👍",
  "👎": "dislike kyu kiya 👎",
  "👌": "wah kya baat hai 👌",
  "🙏": "jawo maaf kiya tujhe 😂🙏",
  "💋": "Abe ye kissi wissi na kiya karo 😏💋",
  "🐒": "mujhe pata hai tum bandar ho 🐒😂",
  "🙈": "sharmao mat apna hi ghar samjho 🙈",
  "🤫": "kyu karu chup, baap ka raaj hai kya 🤫😂",
  "😁": "lagta hai aaj brush kiye ho 😁",
  "🔥": "aag laga di tune toh 🔥",
  "💯": "100% sahi 💯",
  "🎉": "party time 🎉",
  "🌟": "star hai tu 🌟",
  "✨": "chamak raha hai ✨",
  "🌹": "phool de raha hai 🌹",
  "🥀": "murjhaya phool 🥀",
  "😊": "muskarate raho 😊",
  "😇": "itna shareef kab se 😇",
  "🥳": "party ho rahi hai 🥳",
  "😌": "sukoon mil gaya 😌",
  "🤩": "star wali aankhein 🤩",
  "😉": "aankh kyu maar raha hai 😉",
  "😆": "haste raho 😆",
  "😅": "paseena aa gaya 😅",
  "😃": "khushi dekho 😃",
  "😄": "maza aa gaya 😄",
  "🥲": "hasi me rona 🥲",
  "🫶": "dil wala pyaar 🫶",
  "👀": "kya dekh raha hai 👀",
  "👋": "bye bye 👋",
  "👏": "taali bajao 👏",
  "💪": "takath dikha raha hai 💪",
  "💀": "mar gaya kya 💀",
  "😑": "boring lag raha hai kya 😑"
};

module.exports.handleEvent = async function ({ api, event }) {
  const { threadID, messageID, senderID } = event;

  const body = (event.body || "").trim();
  const lowerBody = body.toLowerCase();

  // 🔒 Exact "bot" → random reply
  if (lowerBody === "bot") {
    let displayName = "Jaan";
    try {
      const userInfo = await api.getUserInfo(senderID);
      displayName = userInfo[senderID]?.name || "Jaan";
    } catch (e) {
      displayName = "Jaan";
    }

    const randomReply = responses[Math.floor(Math.random() * responses.length)];
    const finalMsg = `🥀${displayName}😗, ${randomReply}`;

    return api.sendMessage({ body: finalMsg }, threadID, messageID);
  }

  // 😀 Emoji / keyword replies
  for (const key of Object.keys(emojiReplies)) {
    if (body.includes(key)) {
      return api.sendMessage(emojiReplies[key], threadID, messageID);
    }
  }
};

module.exports.run = () => {};
